# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

variables: 
  vmImageName: 'ubuntu-latest'
  environmentName: 'webapp-env'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: BuildandPublishArtifacts
      displayName: BuildwithMaven and PublishBuild Artifacts
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(build.sourcesdirectory)/src/main/resources/db/mysql'
          Contents: '*.sql'
          TargetFolder: '$(build.artifactsstagingdirectory)'
        
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: '$(build.artifactstagingdirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'    



