# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: ubuntu-latest

variables: 
  vmImageName: 'ubuntu-latest'
  environmentName: 'webapp-env'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: BuildandPublishArtifacts
      displayName: BuildwithMaven and PublishBuild Artifacts
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'YAML_ProjectSC'
          KeyVaultName: 'nextopsakv01'
          SecretsFilter: '*'
          RunAsPreJob: true
      
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(build.sourcesdirectory)/env'
          backendServiceArm: 'YAML_ProjectSC'
          backendAzureRmResourceGroupName: 'NextOps'
          backendAzureRmStorageAccountName: 'nextopstfsa01'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'DEV/dev.tfstate'